# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
