# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20180317_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Write about your self'),
        ),
    ]
